service: southwest-checkin

provider:
  name: aws
  runtime: python2.7

# you can overwrite defaults here
#defaults:
#  stage: dev
#  region: us-east-1

package:
  exclude:
    - env/

functions:
  checkin:
    handler: swa.check_in
  getreservation:
    handler: swa.get_reservation

#   you can add any of the following events
#   events:
#     - http:
#         path: users/create
#         method: get
#     - s3: ${bucket}
#     - schedule: rate(10 minutes)
#     - sns: greeter-topic

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
